
# --------------------------------------------------------------------------
#
# WCC386 Options:
#
#      4r  use 80486 timings and register argument passing
#       c  compile only
#      d1  include line number debugging information
#      d2  include full sybolic debugging information
#      ei  force enums to be of type int
#       j  change char default from unsigned to signed
#      oa  relax aliasing checking
#      od  do not optimize
#  oe[=#]  expand functions inline, # = quads (default 20)
#      oi  use the inline library functions
#      om  generate inline 80x87 code for math functions
#      ot  optimize for time
#      ox  maximum optimization
#       s  remove stack overflow checks
#     zp1  align structures on bytes
#      zq  use quiet mode
#  /i=dir  add include directories
#
# --------------------------------------------------------------------------

!ifeq appver_exedef HEXRBETA
BETA=1
!else ifeq appver_exedef HEXDEMOA
BETA=1
!else
BETA=0
!endif

!ifeq BETA 1
LOCOBJS = &
 i_cyber.obj &
 i_ibm.obj &
 i_ibm_a.obj &
 i_sound.obj &
 linear.obj
!else
LOCOBJS = &
 i_cdmus.obj &
 i_cyber.obj &
 i_ibm.obj &
 i_ibm_a.obj &
 i_sound.obj &
 linear.obj
!endif

GLOBOBJS = &
 am_map.obj &
 a_action.obj &
 ct_chat.obj &
 d_net.obj &
 f_finale.obj &
 g_game.obj &
 h2_main.obj &
 info.obj &
 in_lude.obj &
 mn_menu.obj &
 m_misc.obj &
 p_acs.obj &
 p_anim.obj &
 p_ceilng.obj &
 p_doors.obj &
 p_enemy.obj &
 p_floor.obj &
 p_inter.obj &
 p_lights.obj &
 p_map.obj &
 p_maputl.obj &
 p_mobj.obj &
 p_plats.obj &
 p_pspr.obj &
 p_setup.obj &
 p_sight.obj &
 p_spec.obj &
 p_switch.obj &
 p_telept.obj &
 p_tick.obj &
 p_things.obj &
 p_user.obj &
 po_man.obj &
 r_bsp.obj &
 r_data.obj &
 r_draw.obj &
 r_main.obj &
 r_plane.obj &
 r_segs.obj &
 r_things.obj &
 sb_bar.obj &
 sc_man.obj &
 sn_sonix.obj &
 st_start.obj &
 sv_save.obj &
 sounds.obj &
 tables.obj &
 v_video.obj &
 w_wad.obj &
 z_zone.obj

default: .SYMBOLIC
 @echo.
 @echo You must use M.BAT to build Hexen.
 @echo Type "M /?" for help.
 @echo.

#
# DEBUG Build:
#
#  The EXTERNOPT macro should be set to /d2
#
# FINAL Build:
#
#  The EXTERNOPT macro should be set to /dNORANGECHECKING
#

!ifeq appver_exedef HEX11B
VERSION_ID = BCP
VERSIONOPT = /dAPPVER_EXEDEF=$(appver_exedef) /dVER_ID="$(VERSION_ID)"
!else ifeq appver_exedef HEX11A
VERSION_ID = CBI
VERSIONOPT = /dAPPVER_EXEDEF=$(appver_exedef) /dVER_ID="$(VERSION_ID)"
!else
VERSIONOPT = /dAPPVER_EXEDEF=$(appver_exedef)
!endif

!ifeq BETA 1
CCOPTS = $(EXTERNOPT) $(VERSIONOPT) /d2 /omaxet /zp1 /4r /ei /j /zq
!else
CCOPTS = $(EXTERNOPT) $(VERSIONOPT) /omaxet /zp1 /4r /ei /j /zq
!endif

!ifeq use_apodmx 1
DMXINC = /i=..\apodmx
DMXLIBS = lib ..\..\apodmx\apodmx lib audio_wf
!else
DMXINC = /i..\dmx\dmx33gs\inc
DMXLIBS = lib ..\..\dmx\dmx34a\lib\dmx
!endif

!ifeq BETA 1
LNKFILE = hexbeta.lnk
!else ifeq appver_exedef HEXDEMOB
LNKFILE = hexdemob.lnk
!else
LNKFILE = hex.lnk
!endif

$(appver_exedef)\hex.exe : $(LOCOBJS) $(GLOBOBJS)
 cd $(appver_exedef)
 # Workaround for too long path
!ifeq use_apodmx 1
 copy ..\..\audiolib\origlibs\109\AUDIO_WF.LIB .
!endif
 call ..\linkhlpr.bat $(LNKFILE) $(DMXLIBS)
 copy hex.exe striphex.exe
 wstrip striphex.exe
# 4gwbind 4gwpro.exe striphex.exe hexen.exe -V
# ncopy hex.map v_$(VERSION_ID).map
# prsucc
 cd ..

.obj : $(appver_exedef)

!ifeq appver_exedef HEXRBETA
i_ibm.obj: i_ibm.c
 wcc386 /dAPPVER_EXEDEF=$(appver_exedef) /d2 /zp1 /4r /zq /ei /j $(DMXINC) $[* /fo=$(appver_exedef)\$^&
!else ifeq appver_exedef HEXDEMOA # Similar to Heretic
i_ibm.obj: i_ibm.c
 wcc386 /dAPPVER_EXEDEF=$(appver_exedef) /zp1 /4r /zq /ei /j $(DMXINC) $[* /fo=$(appver_exedef)\$^&
!endif

.c.obj :
 wcc386 $(CCOPTS) $(DMXINC) $[* /fo=$(appver_exedef)\$^&

.asm.obj :
!ifeq BETA 1 # For I_ReadJoystick
 tasm /mx /dAPPVER_HEXEN_PUSH16REGS $[*,$(appver_exedef)\$^&/J
!else ifeq appver_exedef HEXDEMOB # Same thing
 tasm /mx /dAPPVER_HEXEN_PUSH16REGS $[*,$(appver_exedef)\$^&/J
!else
 tasm /mx $[*,$(appver_exedef)\$^&/J
!endif
